# This is a basic workflow that is manually triggered

name: CI/CD frontend


on:
  
    push: 
      branches: [ "main"]
      
      

jobs:
  CI:

    runs-on: ubuntu-latest

   
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Verificar estructura
      run: |
        echo "Estructura del repositorio:"
        ls -R
        echo "\nContenido de frontend:"
        ls -la frontend/
